name: flutter_boilerplate
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Storage
  shared_preferences: ^2.2.2

  # View
  flutter_svg: ^2.0.10+1
  
  # Localization
  intl: ^0.19.0
  intl_utils: ^2.8.7

  # DI
  injectable: ^2.4.0
  get_it: ^7.6.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner:
  flutter_lints: ^3.0.0
  flutter_gen_runner:
  injectable_generator:

dependency_overrides:
  meta: 1.11.0

flutter:

  uses-material-design: true

  assets:
    - assets/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flutter_gen:
  output: lib/shared/resources/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true

flutter_intl:
  enabled: true
  class_name: S
  main_locale: en
  arb_dir: lib/shared/l10n 
  output_dir: lib/shared/generated 